### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Bluscream** [Birdgeek/BreadBot#5]
```
blu@homeserver:/opt/irctodiscord$ java -jar 0.0.6.jar
09:31:09 INFO  Discord - Logging in using: discord@fuckingspam.de.vc
Exception in thread "main" java.lang.NoClassDefFoundError: sun/net/spi/nameservice/dns/DNSNameService
        at net.dv8tion.jda.utils.ServiceUtil.loadServices(ServiceUtil.java:95)
        at net.dv8tion.jda.managers.AudioManager.init(AudioManager.java:356)
        at net.dv8tion.jda.managers.AudioManager.<init>(AudioManager.java:58)
        at net.dv8tion.jda.entities.impl.JDAImpl.<init>(JDAImpl.java:79)
        at net.dv8tion.jda.JDABuilder.buildAsync(JDABuilder.java:319)
        at net.dv8tion.jda.JDABuilder.buildBlocking(JDABuilder.java:373)
        at com.github.birdgeek.breadbot.discord.DiscordMain.setup(DiscordMain.java:29)
        at com.github.birdgeek.breadbot.BotMain.main(BotMain.java:47)
Caused by: java.lang.ClassNotFoundException: sun.net.spi.nameservice.dns.DNSNameService
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
        at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
        ... 8 more
blu@homeserver:/opt/irctodiscord$
```

**Comment by Birdgeek** [comment]
@Bluscream, as of last year (2016) I decided to stop development on BreadBot. The way the bot was coded will no longer work due to discord updating the way bots access the API. I apologize for the inconvenience but I will not be providing support for BreadBot any longer.
